name: CI Docker C++ Build

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    # Кеш для Conan
    - name: Cache Conan
      uses: actions/cache@v4
      with:
        path: ~/.conan2
        key: ${{ runner.os }}-conan2-${{ hashFiles('conanfile.*') }}
        restore-keys: |
          ${{ runner.os }}-conan2-

    # Кеш Docker слоев (ускоряет docker build)
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        load: true
        tags: my-cpp-app:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Run tests inside Docker
      run: docker run --rm my-cpp-app
      # или например docker run --rm my-cpp-app ./build/my_tests


